### ISSUE TITLE
build on rapsberry directly ?

### ISSUE THREAD

**Issue by ZechariahZheng** [arminkz/lanberry#2]

**Comment by arminkz** [comment]
yes, but if you need to build it on another machine/architecture you will need to use docker for the building.
use this command: `make docker-linux-arm`

**Comment by ZechariahZheng** [comment]
Thanks for your answer. but I have tried: make docker-linux-arm, it failed. 
Docker can't install ARM EABI toolchain, because the [link](https://copr.fedoraproject.org/coprs/lantw44/arm-linux-gnueabi-toolchain/repo/fedora-21/lantw44-arm-linux-gnueabi-toolchain-fedora-21.repo)  in Dockerfile doesn't exist. Have ever you build docker successfully?
`RUN yum install -y yum-utils && \
  rpm --import https://copr-be.cloud.fedoraproject.org/results/lantw44/arm-linux-gnueabi-toolchain/pubkey.gpg && \
  yum-config-manager --add-repo=https://copr.fedoraproject.org/coprs/lantw44/arm-linux-gnueabi-toolchain/repo/fedora-21/lantw44-arm-linux-gnueabi-toolchain-fedora-21.repo && \
  yum install -y arm-linux-gnueabi-gcc arm-linux-gnueabi-binutils arm-linux-gnueabi-glibc && \
  yum clean packages
`

**Comment by arminkz** [comment]
I tried it on my x64 ubuntu and the build was successful.
so **NO, you do not need to build on raspberry pi itself**. sorry for misinformation.
the same `make linux-arm` will work.

also in the new version (5.6.4 by the time of writing this) you will need to modify a few lines of code in order to build successfully for more info see #1
